name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Caso 1
      id: caso-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Caso 1
        setup-command: ''
        command: python calcula_peso_ideal.py
        input: |-
          1.75
          F
        expected-output: '63.97'
        comparison-method: contains
        timeout: 5
    - name: Caso 2
      id: caso-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Caso 2
        setup-command: ''
        command: python calcula_peso_ideal.py
        input: |-
          1.90
          M
        expected-output: '80.13'
        comparison-method: contains
        timeout: 5
    - name: Caso 3
      id: caso-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Caso 3
        setup-command: ''
        command: python calcula_peso_ideal.py
        input: |-
          1.90
          F
        expected-output: '73.29'
        comparison-method: contains
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CASO-1_RESULTS: "${{steps.caso-1.outputs.result}}"
        CASO-2_RESULTS: "${{steps.caso-2.outputs.result}}"
        CASO-3_RESULTS: "${{steps.caso-3.outputs.result}}"
      with:
        runners: caso-1,caso-2,caso-3
